name: Add Course

on:
  issues:
    types:
      - labeled

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  add-course:
    if: github.event.label.name == 'course'
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: 🔨 add course file
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const script = require('./scripts/course-create.js');
            await script({github, context, core, exec, io});

      - name: 🚀 commit & push changes
        uses: actions-js/push@master
        with:
          message: "Fixed #${{ github.event.issue.number }}. Generated ${{ github.event.issue.title }}."
          github_token: ${{ secrets.PAT }}
